### PR TITLE
Customize swagger with Safe logo

### PR DESCRIPTION
**Pull request by Uxio0**
- Add configuration for templates and static files
- Add collect static to Dockerfile
- Don't rebuild docker image unless dependencies change

### CODE REVIEW

**Review by moisses89 — APPROVED** [review]
`logo.svg` it's included but never used.

**Review by fmrsabino — APPROVED** [review]

**Review by fmrsabino — CHANGES_REQUESTED** [review]
Can we remove `logo.svg` if it's not being used? Just read @moisses89 comment

**Comment by Uxio0** [comment]
Logo.svg has been removed 😉

**Review by fmrsabino — APPROVED** [review]
🚀

**Pull request merged**
