### PR TITLE
Add hidden field to Chain model

### LINKED ISSUE #833: Add a property for Chain to hide
**Background**
- Adding a chain is a very tedious process
- We need to add chains temporary to do proper QA before releasing
- After adding a chain, removing and doing QA it could be possible that when we add it again we make a mistake and chain is not working as expected

**Describe the solution you'd like**
- A `hidden` field that will remove a `Chain` from every result

### PR DESCRIPTION
**Pull request by hectorgomezv**
Closes #833 

This PR adds the `hidden` property to `Chain` model, with its default value set to `False`. This property makes it possible to mark a chain as hidden, so it can be created/configured beforehand. A chain will be only visible through the API when this `hidden` property is set to `False`.

### CODE REVIEW

**Review by Uxio0 — CHANGES_REQUESTED** [review]
I would add one test and update the factories with the hidden field: https://github.com/safe-global/safe-config-service/blob/main/src/chains/tests/factories.py#L14

**Comment by fmrsabino** [comment]
> I would add one test and update the factories with the hidden field: https://github.com/safe-global/safe-config-service/blob/main/src/chains/tests/factories.py#L14

Also maybe a migration test to make sure that previous available chains are visible once the migrations is applied.

**Comment by hectorgomezv** [comment]
> I would add one test and update the factories with the hidden field: https://github.com/safe-global/safe-config-service/blob/main/src/chains/tests/factories.py#L14

I've added the `hidden` property to the `ChainFactory` class, and also some tests verifying the hidden chains get ignored by the list response and the client gets a 404 when requesting the detail view of a hidden chain in [989ea03](https://github.com/safe-global/safe-config-service/pull/835/commits/989ea0308e8d33cffadf531879fde191a85fd77f)

**Review by Uxio0 — APPROVED** [review]

**Comment by Uxio0** [comment]
Looks good to me, thanks for implementing this @hectorgomezv !

**Pull request merged**
